name: Release
on:
  push:
    branches: [main]

permissions:
  contents: write
  issues: write
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun i
      # NOTE https://github.com/semantic-release/npm/issues/280
      - run: alias npm=bun
      - run: npm run release
